### PR TITLE
gamepad: create different names for each device

### PR DESCRIPTION
**Pull request by aristeu**
To better distinguish which device is which and keep the application
from reordering (Lakka), add the number of the device to the name.

### CODE REVIEW

**Comment by karlvr** [comment]
I have tried this and it does what it says! As it renames the devices, I had to reconfigure ES input mappings. This sounds like a good idea.

**Comment by petrockblog** [comment]
@karlvr This does not automatically merge now. Could you take another look into that?

**Comment by aristeu** [comment]
I'll rebase it

**Comment by aristeu** [comment]
Rebased. Also fixed a build error in src/input_xarcade.c (charbuffer doesn't exist anymore; 9eba00976a87a60e34914a0ade966fff79689ccb)

**Pull request merged**
