### PR TITLE
Fix simulated keypresses by introducing a sleep between the down and up events

### PR DESCRIPTION
**Pull request by karlvr**
Advmame in particular expected this otherwise BTN_SELECT didn't work. I arrived at the sleep value of 100000 after some basic testing. 10000 was too short.

I'll experiment with some values between 100000 and 10000.

I've put the sleeps into the uinput files and made one for kbd and gpad respectively in case we determine that the values need to be different for them?

### CODE REVIEW

**Comment by karlvr** [comment]
Related to #11

**Comment by karlvr** [comment]
Sleep investigation: 50000 appears to work just as well as 100000. 25000 is intermittent. 30000 is about 90% good.

**Comment by karlvr** [comment]
50,000 definitely seems 100% effective. I'll switch to that over 100,000 and we'll be TWICE as fast :-D

**Comment by petrockblog** [comment]
Thanks again!

**Pull request merged**
