### PR TITLE
Daemonize the xarcade2jstick process

### PR DESCRIPTION
**Pull request by karlvr**
Re #9 

Launching from udev requires that the process detach quickly. Here I have taken some reference detaching/daemonizing code from http://www.itp.uzh.ch/~dpotter/howto/daemonize and detach after successfully opening the various devices.

This corrects the hang I was seeing on launch by udev as it tried to launch xarcade2jstick and waited for it to detach.

Because we daemonize after opening the relevant devices, we still see failure messages on the console. We could take this further and add syslog support! That page linked above has an example of that so I'd be happy to add it.

### CODE REVIEW

**Comment by aristeu** [comment]
What about:
https://github.com/petrockblog/Xarcade2Jstick/commit/665bd1e0429b697b87f6b47572ae8c56f3e7ba26

**Comment by karlvr** [comment]
@aristeu it's nice and simple; check this page http://www.itp.uzh.ch/~dpotter/howto/daemonize

I we believe that author then that simple call is missing some potentially valuable stuff?

**Comment by aristeu** [comment]
@karlvr daemon() should be enough. I'm not sure why the author in that url cared about signal handling for example. The rest, handling file descriptor, creating a new session, forking, changing current directory, are done by daemon(). It does look like the author had no idea daemon() existed
or might be dated before daemon() was ported from BSD to linux.

**Comment by karlvr** [comment]
@aristeu right you are, I was just re-reading the man entry on it. This looks like a great solution!

**Pull request closed without merging**
